package me.archen.owtranspiler.scriptsdk.impl;

public interface Constants {

    //EVENT PARAMETER KEYS
    String EVENT_PLAYER_KEY = "EVENT PLAYER";
    String EVENT_VICTIM_KEY = "VICTIM";
    String EVENT_ATTACKER_KEY = "ATTACKER";
    String EVENT_DAMAGE_KEY = "EVENT DAMAGE";
    String EVENT_WAS_CRITICAL_KEY = "EVENT WAS CRITICAL HIT";

    //VECTOR RELATED
    String VECTOR_NEW = "VECTOR(@1, @2, @3)";
    String VECTOR_FROM_ANGLES = "VECTOR(@1, @2)";
    String VECTOR_X_COMPONENT = "X COMPONENT OF(@0)";
    String VECTOR_Y_COMPONENT = "Y COMPONENT OF(@0)";
    String VECTOR_Z_COMPONENT = "Z COMPONENT OF(@0)";
    String VECTOR_NORMALIZE = "NORMALIZE(@0)";

    String VECTOR_ADD = "ADD(@0, @1)";
    String VECTOR_SUBTRACT = "SUBTRACT(@0, @1)";
    String VECTOR_MULTIPLY = "MULTIPLY(@0, @1)";
    String VECTOR_DIVIDE = "DIVIDE(@0, @1)";

    String VECTOR_DOT_PRODUCT = "DOT PRODUCT(@0, @1)";
    String VECTOR_CROSS_PRODUCT = "CROSS PRODUCT(@0, @1)";
    String VECTOR_DIRECTION_TOWARDS = "DIRECTION TOWARDS(@0, @1)";
    String VECTOR_DISTANCE_TO = "DISTANCE BETWEEN(@0, @1)";

    String HORIZONTAL_ANGLE_FROM_DIRECTION = "HORIZONTAL ANGLE FROM DIRECTION(@0)";
    String VERTICAL_ANGLE_FROM_DIRECTION = "VERTICAL ANGLE FROM DIRECTION(@0)";

    //PLAYER RELATED
    String PLAYER_POSITION = "POSITION OF(@0)";
    String PLAYER_EYE_POSITION = "EYE POSITION(@0)";
    String PLAYER_IS_CONNECTED = "ENTITY EXISTS(@0)";
    String PLAYER_IS_ALIVE = "IS ALIVE(@0)";
    String PLAYER_GET_HERO = "HERO OF(@0)";
    String PLAYER_GET_TEAM = "TEAM OF(@0)";
    String PLAYER_HAS_SPAWNED = "HAS SPAWNED(@0)";
    String PLAYER_HEALTH = "HEALTH(@0)";
    String PLAYER_HEALTH_PERCENT = "HEALTH PERCENT(@0)";
    String PLAYER_MAX_HEALTH = "MAX HEALTH(@0)";
    String PLAYER_IS_ON_GROUND = "IS ON GROUND(@0)";
    String PLAYER_IS_ON_OBJECTIVE = "IS ON OBJECTIVE(@0)";
    String PLAYER_IS_MOVING = "IS MOVING(@0)";
    String PLAYER_IS_ON_WALL = "IS ON WALL(@0)";
    String PLAYER_IS_PORTRAIT_ON_FIRE = "IS PORTRAIT ON FIRE(@0)";
    String PLAYER_IS_USING_ABILITY_1 = "IS USING ABILITY 1(@0)";
    String PLAYER_IS_USING_ABILITY_2 = "IS USING ABILITY 2(@0)";
    String PLAYER_IS_USING_ULTIMATE = "IS USING ULTIMATE(@0)";
    String PLAYER_ULTIMATE_CHARGE_PERCENT = "ULTIMATE CHARGE PERCENT(@0)";
    String PLAYER_IS_FIRING_PRIMARY = "IS FIRING PRIMARY(@0)";
    String PLAYER_IS_FIRING_SECONDARY = "IS FIRING SECONDARY(@0)";
    String PLAYER_IS_CROUCHING = "IS CROUCHING(@0)";
    String PLAYER_GET_SCORE = "SCORE OF(@0)";
    String PLAYER_GET_SLOT = "SLOT OF(@0)";
    String PLAYER_IS_IN_VIEW_ANGLE = "IS IN VIEW ANGLE(@0, @1)";
    String PLAYER_GET_SPEED = "SPEED OF(@0)";
    String PLAYER_GET_THROTTLE = "THROTTLE OF(@0)";
    String PLAYER_GET_VELOCITY = "VELOCITY OF(@0)";
    String PLAYER_GET_VERTICAL_SPEED = "VERTICAL SPEED OF(@0)";
    String PLAYER_GET_HORIZONTAL_SPEED = "VERTICAL SPEED OF(@0)";
    String PLAYER_GET_VERTICAL_ANGLE = "VERTICAL FACING ANGLE OF(@0)";
    String PLAYER_GET_HORIZONTAL_ANGLE = "HORIZONTAL FACING ANGLE OF(@0)";
    String PLAYER_GET_DIRECTION = "FACING DIRECTION OF(@0)";
    String PLAYER_GET_PLAYERS_IN_VIEW_ANGLE = "PLAYERS IN VIEW ANGLE(@0)";
    String PLAYER_HAS_STATUS = "HAS STATUS(@0, @1)";
    String PLAYER_IS_BUTTON_HELD = "IS BUTTON HELD(@0, @1)";
    String PLAYER_GET_ALLOWED_HEROES = "ALLOWED HEROES(@0)";

    String PLAYER_APPLY_IMPULSE = "APPLY IMPULSE(@0, @1, @2, @3, @4)";
    String PLAYER_CLEAR_STATUS = "CLEAR STATUS(@0, @1)";
    String PLAYER_SET_STATUS = "SET STATUS(@0, @3, @1, @2)";
    String PLAYER_DAMAGE = "DAMAGE(@0, @2, @1)";
    String PLAYER_HEAL = "HEAL(@0, @2, @1)";
    String PLAYER_RESURRECT = "RESURRECT(@0)";
    String PLAYER_RESPAWN = "RESPAWN(@0)";
    String PLAYER_SET_RESPAWN_TIME = "SET RESPAWN MAX TIME(@0, @1)";
    String PLAYER_SET_MAX_HEALTH = "SET MAX HEALTH(@0, @1)";
    String PLAYER_SET_HEALING_DEALT = "SET HEALING DEALT(@0, @1)";
    String PLAYER_SET_HEALING_RECEIVED = "SET HEALING RECEIVED(@0, @1)";
    String PLAYER_SET_DAMAGE_DEALT = "SET DAMAGE DEALT(@0, @1)";
    String PLAYER_SET_DAMAGE_RECEIVED = "SET DAMAGE RECEIVED(@0, @1)";
    String PLAYER_START_HEAL_OVER_TIME = "START HEAL OVER TIME(@0, @3, @2, @1)";
    String PLAYER_START_DAMAGE_OVER_TIME = "START DAMAGE OVER TIME(@0, @3, @2, @1)";
    String PLAYER_LAST_DAMAGE_OVER_TIME_ID = "LAST DAMAGE OVER TIME ID";
    String PLAYER_LAST_HEAL_OVER_TIME_ID = "LAST HEAL OVER TIME ID";
    String PLAYER_ALLOW_BUTTON = "ALLOW BUTTON(@0, @1)";
    String PLAYER_DISALLOW_BUTTON = "DISALLOW BUTTON(@0, @1)";
    String PLAYER_START_HOLDING_BUTTON = "START HOLDING BUTTON(@0, @1)";
    String PLAYER_STOP_HOLDING_BUTTON = "STOP HOLDING BUTTON(@0, @1)";
    String PLAYER_PRESS_BUTTON = "PRESS BUTTON(@0, @1)";
    String PLAYER_COMMUNICATE = "COMMUNICATE(@0, @1)";
    String PLAYER_KILL = "KILL(@0, @1)";
    String PLAYER_TELEPORT = "TELEPORT(@0, @1)";
    String PLAYER_SET_FACING = "SET FACING(@0, @1, @2)";
    String PLAYER_SET_MOVE_SPEED = "SET MOVE SPEED(@0, @1)";
    String PLAYER_SET_GRAVITY = "SET GRAVITY(@0, @1)";
    String PLAYER_SET_PROJECTILE_GRAVITY = "SET PROJECTILE GRAVITY(@0, @1)";
    String PLAYER_SET_SCORE = "SET PLAYER SCORE(@0, @1)";
    String PLAYER_SET_ULTIMATE_CHARGE = "SET ULTIMATE CHARGE(@0, @1)";
    String PLAYER_SET_ABILITY_1_ENABLED = "SET ABILITY 1 ENABLED(@0, @1)";
    String PLAYER_SET_ABILITY_2_ENABLED = "SET ABILITY 2 ENABLED(@0, @1)";
    String PLAYER_SET_ULTIMATE_ABILITY_ENABLED = "SET ULTIMATE ABILITY ENABLED(@0, @1)";
    String PLAYER_SET_PRIMARY_FIRE_ENABLED = "SET PRIMARY FIRE ENABLED(@0, @1)";
    String PLAYER_SET_SECONDARY_FIRE_ENABLED = "SET SECONDARY FIRE ENABLED(@0, @1)";
    String PLAYER_FORCE_PLAYER_HERO = "START FORCING PLAYER TO BE HERO(@0, @1)";
    String PLAYER_STOP_FORCING_PLAYER_HERO = "STOP FORCING PLAYER TO BE HERO(@0)";
    String PLAYER_SET_ALLOWED_HEROES = "SET PLAYER ALLOWED HEROES(@0, @1)";
    String PLAYER_RESET_ALLOWED_HEROES = "RESET PLAYER HERO AVAILABILITY(@0)";

    //GLOBAL RELATED
    String HERO_ALL_HEROES = "ALL HEROES";
    String HERO_ICON_STRING = "HERO ICON STRING(@0)";
    String TEAM_GET_OPPOSITE = "OPPOSITE TEAM OF(@0)";
    String GLOBAL_ALL_PLAYERS = "ALL PLAYERS(@1)";
    String GLOBAL_ALL_LIVING_PLAYERS = "ALL LIVING PLAYERS(@1)";
    String GLOBAL_ALL_DEAD_PLAYERS = "ALL DEAD PLAYERS(@1)";
    String GLOBAL_ALL_PLAYERS_ON_OBJECTIVE = "ALL PLAYERS ON OBJECTIVE(@1)";
    String GLOBAL_ALL_PLAYERS_NOT_ON_OBJECTIVE = "ALL PLAYERS NOT ON OBJECTIVE(@1)";
    String GLOBAL_IS_GAME_IN_PROGRESS = "IS GAME IN PROGRESS";
    String GLOBAL_IS_IN_SETUP = "IS IN SETUP";
    String GLOBAL_IS_MATCH_COMPLETE = "IS MATCH COMPLETE";
    String GLOBAL_MATCH_TIME = "MATCH TIME";
    String GLOBAL_MATCH_ROUND = "MATCH ROUND";
    String GLOBAL_NEAREST_WALKABLE_POSITION = "NEAREST WALKABLE POSITION";
    String GLOBAL_TOTAL_TIME_ELAPSED = "TOTAL TIME ELAPSED";


}
